print("python"[1])
print("A sztringek karaktersorozatok. " [5])
print(len("csodálatos"))
print("Rejtély"[:4])
print("k" in "körte")
print("barack" in "sárgabarack")
print("körte" not in "ananász")
print("barack" > "sárgabarack")
print("anansz" < "barack")